// This file is auto-generated by "maintenance/generateTemplateIndex.ts"
// and contains references to all defined templates.
// Do not edit it by hand or your changes will be lost!

import type { TemplateFunction } from "../src/lib/projectGen";

const templates: { name: string, templateFunction: TemplateFunction }[] = [
	{ name: "_eslintignore.ts", templateFunction: require("./_eslintignore") },
	{ name: "_eslintrc_typescript.js.ts", templateFunction: require("./_eslintrc_typescript.js") },
	{ name: "_github/auto-merge.yml.ts", templateFunction: require("./_github/auto-merge.yml") },
	{ name: "_github/dependabot.yml.ts", templateFunction: require("./_github/dependabot.yml") },
	{ name: "_github/workflows/dependabot-auto-merge.yml.ts", templateFunction: require("./_github/workflows/dependabot-auto-merge.yml") },
	{ name: "_gitignore.ts", templateFunction: require("./_gitignore") },
	{ name: "_prettierignore.ts", templateFunction: require("./_prettierignore") },
	{ name: "_prettierrc.js.ts", templateFunction: require("./_prettierrc.js") },
	{ name: "_project-gen.json.ts", templateFunction: require("./_project-gen.json") },
	{ name: "_vscode/extensions.json.ts", templateFunction: require("./_vscode/extensions.json") },
	{ name: "_vscode/settings.json.ts", templateFunction: require("./_vscode/settings.json") },
	{ name: "LICENSE.ts", templateFunction: require("./LICENSE") },
	{ name: "package.json.ts", templateFunction: require("./package.json") },
	{ name: "README.md.ts", templateFunction: require("./README.md") },
	{ name: "src/index.ts.ts", templateFunction: require("./src/index.ts") },
	{ name: "tsconfig.build.json.ts", templateFunction: require("./tsconfig.build.json") },
	{ name: "tsconfig.json.ts", templateFunction: require("./tsconfig.json") },
];
export = templates;
